version: '2.4'

services:
  postgres:
    ports:
      - 5440:5432
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: admin100%
      POSTGRES_USER: admin
    volumes:
      - db-data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment: 
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 90:80
volumes:
  db-data:
